//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_ru2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_ru2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tutor.Resources.Resource.ru2", typeof(Resource_ru2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О нас.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum
        ///Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet, consequuntur eius repellendus eos aliquid molestiae ea laborum ex quibusdam laudantium voluptates placeat consectetur quam aliquam beatae soluta accusantium iusto nihil nesciunt unde veniam magnam repudiandae sapiente.
        ///
        ///Quos, aliquam nam velit impedit minus tenetur beatae voluptas facere sint pariatur! Voluptatibus, quisquam, error, est assumenda corporis inventore illo nesciunt iure aut dolor possimus repellat minima veniam a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutContent {
            get {
                return ResourceManager.GetString("AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О нас.
        /// </summary>
        public static string AboutMH {
            get {
                return ResourceManager.GetString("AboutMH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательное поле.
        /// </summary>
        public static string AboutRequired {
            get {
                return ResourceManager.GetString("AboutRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Украина, Харьков, пр. Науки 14.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить к поиску.
        /// </summary>
        public static string AddSkill {
            get {
                return ResourceManager.GetString("AddSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аноним.
        /// </summary>
        public static string Anonymous {
            get {
                return ResourceManager.GetString("Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать умение.
        /// </summary>
        public static string ChoiceSkill {
            get {
                return ResourceManager.GetString("ChoiceSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательное поле.
        /// </summary>
        public static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментарии.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактная информация.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связь с нами.
        /// </summary>
        public static string ContactMH {
            get {
                return ResourceManager.GetString("ContactMH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательное поле.
        /// </summary>
        public static string CountryRequired {
            get {
                return ResourceManager.GetString("CountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to День рождения.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательное поле.
        /// </summary>
        public static string DateRequired {
            get {
                return ResourceManager.GetString("DateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательое поле.
        /// </summary>
        public static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детали.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Образование.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електроная почта.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательное поле.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Женский.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательное поле.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы в соц. сетях.
        /// </summary>
        public static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст виджет.
        /// </summary>
        public static string FooterH {
            get {
                return ResourceManager.GetString("FooterH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi, dolores, quibusdam architecto voluptatem amet fugiat nesciunt placeat provident cumque accusamus itaque voluptate modi quidem dolore optio velit hic iusto vero praesentium repellat commodi ad id expedita cupiditate repellendus possimus unde?
        ///
        ///Eius consequatur nihil quibusdam! Laborum, rerum, quis, inventore ipsa autem repellat provident assumenda labore soluta minima alias temporibus facere distinctio quas adipisci nam sunt explicabo offi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательное поле.
        /// </summary>
        public static string GenderRequired {
            get {
                return ResourceManager.GetString("GenderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домашняя страница.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фотография.
        /// </summary>
        public static string ImagePath {
            get {
                return ResourceManager.GetString("ImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательное поле.
        /// </summary>
        public static string ImagePathRequired {
            get {
                return ResourceManager.GetString("ImagePathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательное поле.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adipisicing elit. Quo nulla quibusdam cum doloremque incidunt nemo sunt a tenetur omnis odio..
        /// </summary>
        public static string LoginConten2 {
            get {
                return ResourceManager.GetString("LoginConten2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet,.
        /// </summary>
        public static string LoginContent1 {
            get {
                return ResourceManager.GetString("LoginContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в учетную запись.
        /// </summary>
        public static string LoginH {
            get {
                return ResourceManager.GetString("LoginH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginMH {
            get {
                return ResourceManager.GetString("LoginMH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательное поле.
        /// </summary>
        public static string LoginRequired {
            get {
                return ResourceManager.GetString("LoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The difference between involvement and commitment is like an eggs-and-ham breakfast:
        ///the chicken was involved; the pig was committed..
        /// </summary>
        public static string MainContent {
            get {
                return ResourceManager.GetString("MainContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best place to tell people why they are here.
        /// </summary>
        public static string MainHeader {
            get {
                return ResourceManager.GetString("MainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasons to use this template.
        /// </summary>
        public static string MainReason {
            get {
                return ResourceManager.GetString("MainReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque aliquid adipisci aspernatur. Soluta quisquam dignissimos earum quasi voluptate. Amet, dignissimos, tenetur vitae dolor quam iusto assumenda hic reprehenderit?.
        /// </summary>
        public static string MainReason1 {
            get {
                return ResourceManager.GetString("MainReason1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, commodi, sequi quis ad fugit omnis cumque a libero error nesciunt molestiae repellat quos perferendis numquam quibusdam rerum repellendus laboriosam reprehenderit!.
        /// </summary>
        public static string MainReason2 {
            get {
                return ResourceManager.GetString("MainReason2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem, vitae, perferendis, perspiciatis nobis voluptate quod illum soluta minima ipsam ratione quia numquam eveniet eum reprehenderit dolorem dicta nesciunt corporis?.
        /// </summary>
        public static string MainReason3 {
            get {
                return ResourceManager.GetString("MainReason3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias, excepturi, maiores, dolorem quasi reprehenderit illo accusamus nulla minima repudiandae quas ducimus reiciendis odio sequi atque temporibus facere corporis eos expedita?.
        /// </summary>
        public static string MainReason4 {
            get {
                return ResourceManager.GetString("MainReason4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrap-powered.
        /// </summary>
        public static string MainReasonH1 {
            get {
                return ResourceManager.GetString("MainReasonH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fat-free.
        /// </summary>
        public static string MainReasonH2 {
            get {
                return ResourceManager.GetString("MainReasonH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative Commons.
        /// </summary>
        public static string MainReasonH3 {
            get {
                return ResourceManager.GetString("MainReasonH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author&apos;s support.
        /// </summary>
        public static string MainReasonH4 {
            get {
                return ResourceManager.GetString("MainReasonH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мужской.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оценка.
        /// </summary>
        public static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательное поле.
        /// </summary>
        public static string MarkRequired {
            get {
                return ResourceManager.GetString("MarkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальный возраст.
        /// </summary>
        public static string MaxAge {
            get {
                return ResourceManager.GetString("MaxAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательное поле.
        /// </summary>
        public static string MessageRequired {
            get {
                return ResourceManager.GetString("MessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальный возраст.
        /// </summary>
        public static string MinAge {
            get {
                return ResourceManager.GetString("MinAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательное поле.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательное поле.
        /// </summary>
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet,.
        /// </summary>
        public static string RegisterContent1 {
            get {
                return ResourceManager.GetString("RegisterContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adipisicing elit. Quo nulla quibusdam cum doloremque incidunt nemo sunt a tenetur omnis odio..
        /// </summary>
        public static string RegisterContent2 {
            get {
                return ResourceManager.GetString("RegisterContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новый аккаунт.
        /// </summary>
        public static string RegisterH {
            get {
                return ResourceManager.GetString("RegisterH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string RegisterMH {
            get {
                return ResourceManager.GetString("RegisterMH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти репетитора.
        /// </summary>
        public static string SearchH {
            get {
                return ResourceManager.GetString("SearchH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string SearchMH {
            get {
                return ResourceManager.GetString("SearchMH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить сообщение.
        /// </summary>
        public static string SendMess {
            get {
                return ResourceManager.GetString("SendMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВХОД / РЕГИСТРАЦИЯ.
        /// </summary>
        public static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Signin {
            get {
                return ResourceManager.GetString("Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вакансии.
        /// </summary>
        public static string Summaries {
            get {
                return ResourceManager.GetString("Summaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список вакансий.
        /// </summary>
        public static string SummaryList {
            get {
                return ResourceManager.GetString("SummaryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательное поле.
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительная информация.
        /// </summary>
        public static string UserAbout {
            get {
                return ResourceManager.GetString("UserAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список юзеров.
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница пользователя.
        /// </summary>
        public static string UserPage {
            get {
                return ResourceManager.GetString("UserPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string UserPhone {
            get {
                return ResourceManager.GetString("UserPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перечень умений.
        /// </summary>
        public static string UserSkillList {
            get {
                return ResourceManager.GetString("UserSkillList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вакансии.
        /// </summary>
        public static string Vacancies {
            get {
                return ResourceManager.GetString("Vacancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вакансия.
        /// </summary>
        public static string Vacancy {
            get {
                return ResourceManager.GetString("Vacancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список вакансий.
        /// </summary>
        public static string VacancyList {
            get {
                return ResourceManager.GetString("VacancyList", resourceCulture);
            }
        }
    }
}
